[package]
name = "serde_assert"
version = "0.1.0"
edition = "2021"
rust-version = "1.61.0"
license = "MIT OR Apache-2.0"

[dependencies]
hashbrown = "0.13.1"
serde = {version = "1.0.151", default-features = false, features = ["alloc"]}

[build-dependencies]
serde = {version = "1.0.151", default-features = false}

[dev-dependencies]
claims = "0.7.1"
hashbrown = {version = "0.13.1", features = ["serde"]}
serde_bytes = "0.11.8"
serde_derive = "1.0.151"
