[package]
name = "serde_assert"
version = "0.1.0"
edition = "2018"

[dependencies]
hashbrown = {version = "0.13.1", features = ["serde"]}
serde = {version = "1.0.151", default-features = false, features = ["alloc"]}

[build-dependencies]
serde = {version = "1.0.151", default-features = false}

[dev-dependencies]
claims = "0.7.1"
serde_bytes = "0.11.8"
serde_derive = "1.0.151"
