name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.61.0
          - stable
          - beta
          - nightly
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - run: cargo test

  no_std:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.61.0
          - stable
          - beta
          - nightly
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        targets: thumbv6m-none-eabi
    - run: cargo build --target thumbv6m-none-eabi
  
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt
    - run: cargo fmt -- --check

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - run: cargo check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: clippy
    - run: cargo clippy -- --deny warnings

  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - run: cargo doc --no-deps
      env:
        RUSTDOCFLAGS: -D warnings

  msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - run: curl -LsSf https://github.com/foresterre/cargo-msrv/releases/download/v0.17.1/cargo-msrv-x86_64-unknown-linux-gnu-v0.17.1.tgz | tar zxvf - -C ~/.cargo/bin
    - run: mv ~/.cargo/bin/cargo-msrv-x86_64-unknown-linux-gnu-v0.17.1/cargo-msrv ~/.cargo/bin/cargo-msrv
    - run: cargo msrv verify
